server:
  port: 8082

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/db_pay?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  application:
    name: boot-pay-service
dubbo:
  application:
    name: boot-pay-service
  registry:
    address: zookeeper://192.168.31.147:2181
  protocol:
    name: dubbo
    port: 20882
